<article class="data-control-id-1003 bd-article-1 clearfix">
    <?php if ($_header = $this->getHeader()): ?>
    <h2 class="data-control-id-926 bd-postheader-1">
        <?php echo $_header ?>
    </h2>
<?php endif ?>
	
		<?php if ($_content = $this->getContent()): ?>
    <div class="data-control-id-959 bd-postcontent-1 bd-tagstyles">
        <?php echo $_content ?>
    </div>
<?php endif ?>
	
		<ul class="data-control-id-964 bd-pagination pagination">
    <li class="data-control-id-963 bd-paginationitem-1 disabled"><a href="#">Prev</a></li>
<li class="data-control-id-963 bd-paginationitem-1 active"><a href="#">1</a></li>
<li class="data-control-id-963 bd-paginationitem-1"><a href="#">2</a></li>
<li class="data-control-id-963 bd-paginationitem-1"><a href="#">3</a></li>
<li class="data-control-id-963 bd-paginationitem-1"><a href="#">4</a></li>
<li class="data-control-id-963 bd-paginationitem-1"><a href="#">5</a></li>
<li class="data-control-id-963 bd-paginationitem-1"><a href="#">Next</a></li>
</ul>
</article>