<article class="data-control-id-126488 bd-article-79 clearfix">
    <?php if ($_header = $this->getHeader()): ?>
    <h2 class="data-control-id-125931 bd-postheader-12">
        <?php echo $_header ?>
    </h2>
<?php endif ?>
	
		<?php if ($_content = $this->getContent()): ?>
    <div class="data-control-id-125940 bd-postcontent-13 bd-tagstyles">
        <?php echo $_content ?>
    </div>
<?php endif ?>
</article>