<?php if (($_block = $this->getContext())
        && ($_pagerBlock = $_block->getChild('product_list_toolbar_pager'))
        && $_block->getCollection()->setPageSize($_block->getLimit())->getLastPageNumber() > 1): ?>
    <div class="data-control-id-2362 bd-productsgridpagination-1">
        <?php $_pagerBlock->setTemplate('designer/products-grid/pager_1.phtml') ?>
        <?php echo $_block->getPagerHtml() ?>
    </div>
<?php endif ?>