<?php $_items = $this->getCollection(); ?>
<?php if($_items->getSize()): ?>
    <ul class="sitemap">
        <?php foreach ($_items as $_item): ?>
            <li class="level-<?php echo $this->getLevel($_item) ?>" <?php echo $this->getLevel($_item)?'style="padding-left:' . $this->getLevel($_item, 2) . '0px;"':'' ?>><a href="<?php echo $this->getItemUrl($_item) ?>"><?php echo $_item->name ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <?php $_helper = Mage::registry('templateHelper') ?>
    <?php $_title = $this->__('There are no %s available.', $this->getItemsTitle()) ?>
    <?php echo $_helper ? $_helper->getMessagesHelper()->notice($_title) : $_title; ?>
<?php endif ?>