<div class="data-control-id-48075 bd-productsgridbar-28">
    <div class="bd-container-inner">
        <div class="data-control-id-2350 bd-layoutcontainer-27">
    <div class="bd-container-inner">
        <div class="container-fluid">
            <div class="row
                
                ">
                <div class="data-control-id-55013 bd-layoutcolumn-col-8 
 col-md-17">
    <div class="bd-layoutcolumn-8"><div class="bd-vertical-align-wrapper"><div class="data-control-id-2352 bd-typeselector-1">
    
</div></div></div>
</div>
	
		<div class="data-control-id-2346 bd-layoutcolumn-col-53 
 col-md-4">
    <div class="bd-layoutcolumn-53"><div class="bd-vertical-align-wrapper"><?php if ($_helper = Mage::registry('templateHelper')): ?>
    <?php echo $_helper->createTemplate('products-grid/sorter', 1)->setContext($this)->toHtml() ?>
<?php endif ?></div></div>
</div>
	
		<div class="data-control-id-2348 bd-layoutcolumn-col-54 
 col-md-3">
    <div class="bd-layoutcolumn-54"><div class="bd-vertical-align-wrapper"><?php if ($_helper = Mage::registry('templateHelper')): ?>
    <?php echo $_helper->createTemplate('products-grid/per-page', 1)->setContext($this)->toHtml() ?>
<?php endif ?></div></div>
</div>
            </div>
        </div>
    </div>
</div>
    </div>
</div>