<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before') ?>
<div class="data-control-id-2636 bd-shoppingcart cart">
    <div class="data-control-id-2492 bd-carttitle-1">
    <h2><?php echo $this->__('Shopping Cart') ?></h2>
</div>
    <?php echo $this->getChildHtml('form_before') ?>
<form class="data-control-id-2520 bd-shoppingcarttable-1" action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
<?php if ($_formkey = Mage::app()->getLayout()->getBlock('formkey')): ?>
    <?php echo $_formkey->toHtml() ?>
<?php endif ?>
<div class="table-responsive">
<table class="data-control-id-2510 bd-table">
    <col width="1" />
    <col />
    <col width="1" />
    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
        <col width="1" />
    <?php endif ?>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
    <?php endif; ?>
    <col width="1" />
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
    <?php endif; ?>
    <col width="1" />

    <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
    <thead>
    <tr>
        <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
        <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
        <th rowspan="<?php echo $mergedCells; ?>"></th>
        <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
        <?php endif ?>
        <th colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Unit Price') ?></span></th>
        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
        <th colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
        <th rowspan="<?php echo $mergedCells; ?>" class="a-center">&nbsp;</th>
    </tr>
    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <tr>
            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
        </tr>
    <?php endif; ?>
    </thead>
    <tfoot>
    <tr>
        <td colspan="50" class="a-right">
            <div class="data-control-id-117095 bd-container-48 bd-tagstyles">
            <?php if($this->getContinueShoppingUrl()): ?><button class="data-control-id-117089 bd-button" type="button" title="<?php echo $this->__('Continue Shopping') ?>"  onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><?php echo $this->__('Continue Shopping') ?></span></button><?php endif
            ?><button class="data-control-id-117089 bd-button" type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>"><span><?php echo $this->__('Update Shopping Cart'); ?></span>
                </button><button class="data-control-id-117089 bd-button" type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>"
                     id="empty_cart_button"><span><?php echo $this->__('Clear Shopping Cart'); ?></span></button>
            <!--[if lt IE 8]>
            <input type="hidden" id="update_cart_action_container" />
            <script type="text/javascript">
            //<![CDATA[
                Event.observe(window, 'load', function()
                {
                    // Internet Explorer (lt 8) does not support value attribute in button elements
                    $emptyCartButton = $('empty_cart_button');
                    $cartActionContainer = $('update_cart_action_container');
                    if ($emptyCartButton && $cartActionContainer) {
                        Event.observe($emptyCartButton, 'click', function()
                        {
                            $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                            $cartActionContainer.setAttribute('name', 'update_cart_action');
                            $cartActionContainer.setValue('empty_cart');
                        });
                    }

                });
            //]]>
            </script>
            <![endif]-->
            </div>
        </td>
    </tr>
    </tfoot>
    <tbody>
    <?php
        $_i = 1;
        if (!Mage::registry('shopping_cart_row_index')) {
            Mage::register('shopping_cart_row_index', $_i);
        }

        foreach($this->getItems() as $_item) {
            echo $this->getItemHtml($_item);
            Mage::unregister('shopping_cart_row_index');
            Mage::register('shopping_cart_row_index', ++$_i);
        }

        Mage::unregister('shopping_cart_row_index');
    ?>
    </tbody>
</table>
</div>
</form>

    <div class="row">
        <div class="col-md-8">
            <?php if (!$this->getIsVirtual()) echo $this->getChildHtml('shipping') ?>
        </div>

        <div class="col-md-8">
            <?php echo $this->getChildHtml('coupon') ?>
        </div>

        <div class="col-md-8">
            <?php if ($_helper = Mage::registry('templateHelper')): ?>
    <?php echo $_helper->createTemplate('cart/grandtotal')->setContext($this)->toHtml() ?>
<?php endif ?>
        </div>
    </div>

    <?php if (($_cartExtra = trim($this->getChildHtml('checkout.cart.extra'))) && strlen($_cartExtra)): ?>
            <?php echo $_cartExtra ?>
    <?php endif ?>

    <?php if (($_cartCrosssell = trim($this->getChildHtml('crosssell'))) && strlen($_cartCrosssell)): ?>
            <?php echo $_cartCrosssell ?>
    <?php endif ?>

</div>