<?php if ($form && $data): ?>
<div class="data-control-id-2898 bd-reviewform-1">
    <div class="data-control-id-2875 bd-container-39 bd-tagstyles"><h2><?php echo $this->__('Write Your Own Review') ?></h2></div>
    <?php if ($form->getAllowWriteReviewFlag()): ?>
        <form action="<?php echo $form->getAction() ?>" method="post" id="review-form">
            <?php if ($_formkey = Mage::app()->getLayout()->getBlock('formkey')): ?>
                <?php echo $_formkey->toHtml() ?>
            <?php endif ?>
            <fieldset>
                <?php echo $form->getChildHtml('form_fields_before')?>
                <p><?php echo $this->__("You're reviewing:"); ?> <span><?php echo $this->htmlEscape($form->getProductInfo()->getName()) ?></span></p>
                <?php if( $form->getRatings() && $form->getRatings()->getSize()): ?>
                    <span id="input-message-box"></span>
                    <table class="data-table" id="product-review-table">
                        <col />
                        <col width="1" />
                        <col width="1" />
                        <col width="1" />
                        <col width="1" />
                        <col width="1" />
                        <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th><span class="nobr"><?php echo $this->__('1 star') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('2 stars') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('3 stars') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('4 stars') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('5 stars') ?></span></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($form->getRatings() as $_rating): ?>
                            <tr>
                                <th><?php echo $this->escapeHtml($_rating->getRatingCode()) ?></th>
                                <?php foreach ($_rating->getOptions() as $_option): ?>
                                    <td class="value"><input type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" class="radio" /></td>
                                <?php endforeach; ?>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                    <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                <?php endif; ?>
                <p>
                    <label for="nickname_field" class="required"><em>*</em><?php echo $this->__('Nickname') ?></label>
                    <input type="text" name="nickname" id="nickname_field" class="data-control-id-2876 bd-bootstrapinput form-control required-entry" value="<?php echo $this->htmlEscape($data->getNickname()) ?>" />
                </p>

                <p>
                    <label for="summary_field" class="required"><em>*</em><?php echo $this->__('Summary of Your Review') ?></label>
                    <input type="text" name="title" id="summary_field" class="data-control-id-2876 bd-bootstrapinput form-control required-entry" value="<?php echo $this->htmlEscape($data->getTitle()) ?>" />
                </p>

                <p>
                    <label for="review_field" class="required"><em>*</em><?php echo $this->__('Review') ?></label>
                    <textarea name="detail" id="review_field" cols="16" rows="8" class="data-control-id-2876 bd-bootstrapinput form-control required-entry"><?php echo $this->htmlEscape($data->getDetail()) ?></textarea>
                </p>
            </fieldset>
            <button type="submit" title="<?php echo $this->__('Submit Review') ?>" class="data-control-id-2880 bd-button"><?php echo $this->__('Submit Review') ?></button>
        </form>
        <script type="text/javascript">
            //<![CDATA[
            var dataForm = new VarienForm('review-form');
            Validation.addAllThese(
                [
                    ['validate-rating', '<?php echo $this->__('Please select one of each of the ratings above') ?>', function(v) {
                        var trs = $('product-review-table').select('tr');
                        var inputs;
                        var error = 1;

                        for( var j=0; j < trs.length; j++ ) {
                            var tr = trs[j];
                            if( j > 0 ) {
                                inputs = tr.select('input');

                                for( i in inputs ) {
                                    if( inputs[i].checked == true ) {
                                        error = 0;
                                    }
                                }

                                if( error == 1 ) {
                                    return false;
                                } else {
                                    error = 1;
                                }
                            }
                        }
                        return true;
                    }]
                ]
            );
            //]]>
        </script>
    <?php else: ?>
        <p class="review-nologged" id="review-form">
            <?php echo $this->__('Only registered users can write reviews. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $form->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
        </p>
    <?php endif ?>
</div>
<?php endif ?>