<div class="data-control-id-3220 bd-checkoutsteps-1" id="checkout-progress-state">
    <?php foreach ($this->getSteps() as $_step): ?>
        <a class="data-control-id-3219 bd-checkoutstep-1 <?php if($_step->getIsActive()): ?>active<?php endif ?>">
            <span class="data-control-id-3218 bd-checkoutstepnumber-1"></span>
            <span><?php echo $_step->getLabel() ?></span>
        </a>
    <?php endforeach ?>
</div>