<div class=" bd-block">
    <div class=" bd-blockheader bd-tagstyles">
        <h4><?php echo $this->__('Discount Codes') ?></h4>
    </div>
    <div class=" bd-blockcontent bd-tagstyles">
        <form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
            <div class="discount">
                <div class="discount-form">
                    <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
                    <input type="hidden" name="remove" id="remove-coupone" value="0" />
                    <div class="input-box">
                        <input class="input-text" id="coupon_code" type="text" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
                    </div>
                    <div class="buttons-set left">
                        <button class=" bd-button" type="button" title="<?php echo $this->__('Apply Coupon') ?>"  onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
                        <?php if(strlen($this->getCouponCode())): ?>
                            &nbsp; <button class=" bd-button" type="button" title="<?php echo $this->__('Cancel Coupon') ?>"  onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><span><span><?php echo $this->__('Cancel Coupon') ?></span></span></button>
                        <?php endif;?>
                    </div>
                </div>
            </div>
        </form>
        <script type="text/javascript">
        //<![CDATA[
        var discountForm = new VarienForm('discount-coupon-form');
        discountForm.submit = function (isRemove) {
            if (isRemove) {
                $('coupon_code').removeClassName('required-entry');
                $('remove-coupone').value = "1";
            } else {
                $('coupon_code').addClassName('required-entry');
                $('remove-coupone').value = "0";
            }
            return VarienForm.prototype.submit.bind(discountForm)();
        }
        //]]>
        </script>
    </div>
</div>